from fastapi import APIRouter, Form, UploadFile, File, HTTPException
from pathlib import Path
import json
import shutil
from datetime import datetime

from utils.database import get_db
from models.quiz import obj_id_to_str
from utils.quiz_gen import QuizGenerator
from utils.text_extraction import FileTextExtractor


TEMP_DIR = Path("temp")
TEMP_DIR.mkdir(exist_ok=True)  # create temp folder if not exists

async def save_quiz_to_db(questions, created_by, title):
    db = await get_db()
    quiz_data = {"title": title, "questions": questions, "created_by": created_by, "created_at": str(datetime.now())}
    result = await db.quiz.insert_one(quiz_data)
    new_quiz = await db.quiz.find_one({"_id": result.inserted_id})
    return obj_id_to_str(new_quiz)

def save_uploaded_file(file: UploadFile) -> Path:
    temp_path = TEMP_DIR / file.filename
    with open(temp_path, "wb") as f:
        shutil.copyfileobj(file.file, f)
    return temp_path

router = APIRouter()

@router.post("/text")
async def generate_quiz_from_text(
    title: str = Form(...),
    text: str = Form(...),
    count: int = Form(5),
    qtype: str = Form("mcq"),
    difficulty: str = Form("medium"),
    option_count: int = Form(4),
    created_by: str = Form(...)
):
    """
    Generate quiz from raw text and save to DB.
    """
    quiz_gen = QuizGenerator()
    quiz_json = quiz_gen.generate_as_json(
        text=text,
        count=count,
        qtype=qtype,
        difficulty=difficulty,
        option_count=option_count
    )
    questions = json.loads(quiz_json)
    return await save_quiz_to_db(questions["questions"], created_by, title)


@router.post("/pdf")
async def generate_quiz_from_pdf(
    title: str = Form(...),
    file: UploadFile = File(...),
    count: int = Form(5),
    qtype: str = Form("mcq"),
    difficulty: str = Form("medium"),
    option_count: int = Form(4),
    created_by: str = Form(...)
):
    """
    Generate quiz from PDF file and save to DB.
    """
    temp_path = save_uploaded_file(file)
    text = FileTextExtractor.extract_text(str(temp_path))
    temp_path.unlink()

    if not text.strip():
        raise HTTPException(status_code=400, detail="No text found in PDF")

    quiz_gen = QuizGenerator()
    quiz_json = quiz_gen.generate_as_json(
        text=text,
        count=count,
        qtype=qtype,
        difficulty=difficulty,
        option_count=option_count
    )
    questions = json.loads(quiz_json)
    return await save_quiz_to_db(questions["questions"], created_by, title)


@router.post("/ppt")
async def generate_quiz_from_ppt(
    title: str = Form(...),
    file: UploadFile = File(...),
    count: int = Form(5),
    qtype: str = Form("mcq"),
    difficulty: str = Form("medium"),
    option_count: int = Form(4),
    created_by: str = Form(...)
):
    """
    Generate quiz from PPT file and save to DB.
    """
    temp_path = save_uploaded_file(file)
    text = FileTextExtractor.extract_text(str(temp_path))
    temp_path.unlink()

    if not text.strip():
        raise HTTPException(status_code=400, detail="No text found in PPT")

    quiz_gen = QuizGenerator()
    quiz_json = quiz_gen.generate_as_json(
        text=text,
        count=count,
        qtype=qtype,
        difficulty=difficulty,
        option_count=option_count
    )
    questions = json.loads(quiz_json)
    return await save_quiz_to_db(questions["questions"], created_by, title)

@router.get("/{id}")
async def get_quiz_from_id(
    id: str,
):
    """
    Get all the quiz generated by the user with given id
    """
    db = await get_db()
    cursor = db.quiz.find({"created_by": id})

    quizzes = []
    async for quiz in cursor:
        quiz["id"] = str(quiz["_id"])
        del quiz["_id"]
        quizzes.append(quiz)

    if not quizzes:
        raise HTTPException(status_code=404, detail="No quizzes found for this user")

    return {"quizzes": quizzes}